version: '3.9'

services:
  app:
    image: ghcr.io/luciferianink/chat.petals.ml:latest
    restart: unless-stopped
    ulimits:
      memlock: -1
      stack: 67108864
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    ports:
      - 5000:5000
    volumes:
      # - ./cache:/root/.cache
      - ./static:/app/static

# volumes:
#   cache: